# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0002_auto_20190401_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='projects_posted',
            field=models.IntegerField(null=True),
        ),
    ]
