# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0003_content_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='awwards.Image'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='content',
        ),
        migrations.AddField(
            model_name='rating',
            name='content',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
    ]
