# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0004_auto_20190403_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_caption',
            new_name='project_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='image_name',
        ),
        migrations.AddField(
            model_name='image',
            name='project',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='image',
            name='project_description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='project_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
