# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20190403_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
